In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, f1_score,roc_curve,roc_auc_score
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split,cross_val_score
import warnings
import itertools
import matplotlib as plt
warnings.filterwarnings("ignore")

In [ ]:
data3 = pd.read_csv("QCM3.csv")
data6 = pd.read_csv("QCM6.csv")
data7 = pd.read_csv("QCM7.csv")
data10 = pd.read_csv("QCM10.csv")
data12 = pd.read_csv("QCM12.csv")
dataset = pd.read_csv("Dataset.csv")

In [ ]:
#MLP FOR SENSOR 3
from sklearn.neural_network import MLPClassifier

#SPLITTING INTO X AND Y
x = data3.iloc[:,:10].values
y = data3['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP3=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP3 = (TP / float(TP + FN))
conf_specificityMLP3 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP3,2)}') 
print(f'Specificity: {round(conf_specificityMLP3,2)}') 


Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#MLP FOR SENSOR 6
#SPLITTING INTO X AND Y
x = data6.iloc[:,:10].values
y = data6['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP3=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP6 = (TP / float(TP + FN))
conf_specificityMLP6 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP6,2)}') 
print(f'Specificity: {round(conf_specificityMLP6,2)}') 


Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#MLP FOR SENSOR 7
#SPLITTING INTO X AND Y
x = data7.iloc[:,:10].values
y = data7['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP3=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP7 = (TP / float(TP + FN))
conf_specificityMLP7 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP7,2)}') 
print(f'Specificity: {round(conf_specificityMLP7,2)}') 


Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#MLP FOR SENSOR 10
#SPLITTING INTO X AND Y
x = data10.iloc[:,:10].values
y = data10['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP10=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP10 = (TP / float(TP + FN))
conf_specificityMLP10 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP10,2)}') 
print(f'Specificity: {round(conf_specificityMLP10,2)}') 

Accuracy score: 0.8

Confusion matrix: 
[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 0.8000000000000002
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#MLP FOR SENSOR 12
#SPLITTING INTO X AND Y
x = data12.iloc[:,:10].values
y = data12['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP10=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP12 = (TP / float(TP + FN))
conf_specificityMLP12 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP12,2)}') 
print(f'Specificity: {round(conf_specificityMLP12,2)}') 

Accuracy score: 0.8

Confusion matrix: 
[[1 0 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 0.8000000000000002
Sensitivity: 0.5
Specificity: 1.0


In [ ]:
#SVM FOR SENSOR 3
from sklearn.svm import SVC

#SPLITTING INTO X AND Y
x = data3.iloc[:,:10].values
y = data3['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM3=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM3 = (TP / float(TP + FN))
conf_specificitySVM3 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM3,2)}') 
print(f'Specificity: {round(conf_specificitySVM3,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#SVM FOR SENSOR 6

#SPLITTING INTO X AND Y
x = data6.iloc[:,:10].values
y = data6['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM6=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM6 = (TP / float(TP + FN))
conf_specificitySVM6 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM6,2)}') 
print(f'Specificity: {round(conf_specificitySVM6,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#SVM FOR SENSOR 7

#SPLITTING INTO X AND Y
x = data7.iloc[:,:10].values
y = data7['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM7=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM7 = (TP / float(TP + FN))
conf_specificitySVM7 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM7,2)}') 
print(f'Specificity: {round(conf_specificitySVM7,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#SVM FOR SENSOR 10

#SPLITTING INTO X AND Y
x = data10.iloc[:,:10].values
y = data10['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM10=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM10 = (TP / float(TP + FN))
conf_specificitySVM10 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM7,2)}') 
print(f'Specificity: {round(conf_specificitySVM7,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#SVM FOR SENSOR 12

#SPLITTING INTO X AND Y
x = data12.iloc[:,:10].values
y = data12['Class'].values

#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM12=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM12 = (TP / float(TP + FN))
conf_specificitySVM12 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM12,2)}') 
print(f'Specificity: {round(conf_specificitySVM12,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
pip install hmmlearn

In [ ]:
#K MEANS FOR SENOR 3
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#SPLITTING INTO X AND Y
x=data3.drop('Class',axis=1)
y = data3['Class']
sc=MinMaxScaler()
xsc=sc.fit_transform(x)
xsc=pd.DataFrame(xsc)

#MODELCREATION 
km = KMeans(n_clusters=5)
y_pred=km.fit_predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMM3=str(accuracy_score(y, y_pred))
conf_sensitivityKMM3 = (TP / float(TP + FN))
conf_specificityKMM3 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMM3,2)}') 
print(f'Specificity: {round(conf_specificityKMM3,2)}') 

Accuracy score: 0.6

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 0 5 0]
 [0 0 5 0 0]
 [0 0 0 0 5]]
F1 score: 0.6
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#K MEANS FOR SENSOR 6
#SPLITTING INTO X AND Y
x=data6.drop('Class',axis=1)
y = data6['Class']
sc=MinMaxScaler()
xsc=sc.fit_transform(x)
xsc=pd.DataFrame(xsc)

#MODELCREATION 
km = KMeans(n_clusters=5,random_state=8)
y_pred=km.fit_predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMM6=str(accuracy_score(y, y_pred))
conf_sensitivityKMM6 = (TP / float(TP + FN))
conf_specificityKMM6 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMM6,2)}') 
print(f'Specificity: {round(conf_specificityKMM6,2)}') 

Accuracy score: 0.6

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 0 5 0]
 [0 0 5 0 0]
 [0 0 0 0 5]]
F1 score: 0.6
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#K MEANS FOR SENOR 10
#SPLITTING INTO X AND Y
x=data10.drop('Class',axis=1)
y = data10['Class']
sc=MinMaxScaler()
xsc=sc.fit_transform(x)


#MODELCREATION 
km = KMeans(n_clusters=3,random_state=8)
y_pred=km.fit_predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMM10=str(accuracy_score(y, y_pred))
conf_sensitivityKMM10 = (TP / float(TP + FN))
conf_specificityKMM10 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMM10,2)}') 
print(f'Specificity: {round(conf_specificityKMM10,2)}') 

Accuracy score: 0.6

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]]
F1 score: 0.6
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#K MEANS FOR SENOR 7
#SPLITTING INTO X AND Y
x=data7.drop('Class',axis=1)
y = data7['Class']
sc=MinMaxScaler()
xsc=sc.fit_transform(x)


#MODELCREATION 
km = KMeans(n_clusters=2,random_state=17)
y_pred=km.fit_predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMM7=str(accuracy_score(y, y_pred))
conf_sensitivityKMM7 = (TP / float(TP + FN))
conf_specificityKMM7 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMM7,2)}') 
print(f'Specificity: {round(conf_specificityKMM7,2)}') 

Accuracy score: 0.4

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 5 0 0 0]
 [5 0 0 0 0]
 [0 5 0 0 0]]
F1 score: 0.4000000000000001
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#K MEANS FOR SENOR 12
#SPLITTING INTO X AND Y
x=data12.drop('Class',axis=1)
y = data12['Class']
sc=MinMaxScaler()
xsc=sc.fit_transform(x)


#MODELCREATION 
km = KMeans(n_clusters=4,random_state=8)
y_pred=km.fit_predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMM12=str(accuracy_score(y, y_pred))
conf_sensitivityKMM12 = (TP / float(TP + FN))
conf_specificityKMM12 = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMM12,2)}') 
print(f'Specificity: {round(conf_specificityKMM12,2)}') 

Accuracy score: 0.8

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 5 0 0 0]]
F1 score: 0.8000000000000002
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
!pip install fuzzy-c-means
from fcmeans import FCM

In [ ]:
#FCM FOR SENSOR 3
x=data3.drop('Class',axis=1)
y = data3['Class']

sc=MinMaxScaler()
xsc=sc.fit_transform(x)
#MODEL CREATION
fcm = FCM(n_clusters=5)
fcm.fit(xsc)
y_pred=fcm.predict(xsc)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y, y_pred)))
cm=confusion_matrix(y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y, y_pred)))
print("F1 score: " + str(f1_score(y, y_pred,average='micro')))
TP3 = cm[1][1]
TN3 = cm[0][0]
FP3 = cm[0][1]
FN3 = cm[1][0]
accFC3=str(accuracy_score(y, y_pred))
conf_sensitivityFC3 = (TP3 / float(TP3 + FN3))
conf_specificityFC3 = (TN3 / float(TN3 + FP3))
print(f'Sensitivity: {round(conf_sensitivityFC3,2)}') 
print(f'Specificity: {round(conf_specificityFC3,2)}') 

Accuracy score: 0.44

Confusion matrix: 
[[2 0 3 0 0]
 [0 5 0 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]
 [0 1 0 0 4]]
F1 score: 0.44
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#FCM FOR SENSOR 6
x6=data6.drop('Class',axis=1)
y6 = data6['Class']

sc=MinMaxScaler()
xsc6=sc.fit_transform(x)
#MODEL CREATION
fcm6 = FCM(n_clusters=5)
fcm6.fit(xsc6)
y_pred6=fcm6.predict(xsc6)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y6, y_pred6)))
cm=confusion_matrix(y6, y_pred6)
print("\nConfusion matrix: \n" + str(confusion_matrix(y6, y_pred6)))
print("F1 score: " + str(f1_score(y6, y_pred6,average='micro')))
TP6 = cm[1][1]
TN6 = cm[0][0]
FP6 = cm[0][1]
FN6 = cm[1][0]
accFC6=str(accuracy_score(y6, y_pred6))
conf_sensitivityFC6 = (TP6 / float(TP6 + FN6))
conf_specificityFC6 = (TN6 / float(TN6 + FP6))
print(f'Sensitivity: {round(conf_sensitivityFC6,2)}') 
print(f'Specificity: {round(conf_specificityFC6,2)}') 

Accuracy score: 0.52

Confusion matrix: 
[[3 0 0 2 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 0 5]
 [0 5 0 0 0]]
F1 score: 0.52
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#FCM FOR SENSOR 7
x7=data7.drop('Class',axis=1)
y7 = data7['Class']

sc=MinMaxScaler()
xsc7=sc.fit_transform(x)
#MODEL CREATION
fcm7 = FCM(n_clusters=5)
fcm7.fit(xsc7)
y_pred7=fcm7.predict(xsc7)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y7, y_pred7)))
cm=confusion_matrix(y7, y_pred7)
print("\nConfusion matrix: \n" + str(confusion_matrix(y7, y_pred7)))
print("F1 score: " + str(f1_score(y7, y_pred7,average='micro')))
TP7 = cm[1][1]
TN7 = cm[0][0]
FP7 = cm[0][1]
FN7 = cm[1][0]
accFC7=str(accuracy_score(y7, y_pred7))
conf_sensitivityFC7 = (TP7 / float(TP7 + FN7))
conf_specificityFC7 = (TN7 / float(TN7 + FP7))
print(f'Sensitivity: {round(conf_sensitivityFC7,2)}') 
print(f'Specificity: {round(conf_specificityFC7,2)}') 


Accuracy score: 0.6

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 0 5 0]
 [0 0 5 0 0]
 [0 0 0 0 5]]
F1 score: 0.6
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#FCM FOR SENSOR 10
x10=data10.drop('Class',axis=1)
y10 = data10['Class']

sc=MinMaxScaler()
xsc10=sc.fit_transform(x)
#MODEL CREATION
fcm10 = FCM(n_clusters=5)
fcm10.fit(xsc)
y_pred10=fcm.predict(xsc10)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y10, y_pred10)))
cm=confusion_matrix(y10, y_pred10)
print("\nConfusion matrix: \n" + str(confusion_matrix(y10, y_pred10)))
print("F1 score: " + str(f1_score(y10, y_pred10,average='micro')))
TP10 = cm[1][1]
TN10 = cm[0][0]
FP10 = cm[0][1]
FN10 = cm[1][0]
accFC10=str(accuracy_score(y10, y_pred10))
conf_sensitivityFC10 = (TP10 / float(TP10 + FN10))
conf_specificityFC10 = (TN10 / float(TN10 + FP10))
print(f'Sensitivity: {round(conf_sensitivityFC10,2)}') 
print(f'Specificity: {round(conf_specificityFC10,2)}') 

Accuracy score: 0.52

Confusion matrix: 
[[3 0 2 0 0]
 [0 5 0 0 0]
 [0 0 0 0 5]
 [0 0 0 5 0]
 [0 5 0 0 0]]
F1 score: 0.52
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#FCM FOR SENSOR 12
x12=data12.drop('Class',axis=1)
y12 = data12['Class']

sc=MinMaxScaler()
xsc12=sc.fit_transform(x)
#MODEL CREATION
fcm12 = FCM(n_clusters=5)
fcm12.fit(xsc12)
y_pred12=fcm12.predict(xsc12)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y12, y_pred12)))
cm=confusion_matrix(y12, y_pred12)
print("\nConfusion matrix: \n" + str(confusion_matrix(y12, y_pred12)))
print("F1 score: " + str(f1_score(y12, y_pred12,average='micro')))
TP12 = cm[1][1]
TN12 = cm[0][0]
FP12 = cm[0][1]
FN12 = cm[1][0]
accFC12=str(accuracy_score(y12, y_pred12))
conf_sensitivityFC12 = (TP12 / float(TP12 + FN12))
conf_specificityFC12 = (TN12 / float(TN12 + FP12))
print(f'Sensitivity: {round(conf_sensitivityFC12,2)}') 
print(f'Specificity: {round(conf_specificityFC12,2)}') 

Accuracy score: 0.68

Confusion matrix: 
[[2 0 0 0 3]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 5 0 0 0]]
F1 score: 0.68
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
!pip install mrmr_selection

     |████████████████████████████████| 80 kB 5.4 MB/s 


In [ ]:
from mrmr import mrmr_classif
dataset.head()
dataset.columns=['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10',
              'f11','f12','f13','f14','f15','f16','f17','f18','f19','f20',
              'f21','f22','f23','f24','f25','f26','f27','f28','f29','f30',
              'f31','f32','f33','f34','f35','f36','f37','f38','f39','f40',
              'f41','f42','f43','f44','f45','f46','f47','f48','f49','f50','Class']
X=dataset[dataset.columns[~dataset.columns.isin(['Class'])]]
Y=dataset["Class"]

selected_features = mrmr_classif(X, Y, K = 10)
X_upt=X[selected_features]
sx=sc.fit_transform(X_upt)


100%|██████████| 10/10 [00:00<00:00, 21.34it/s]


In [ ]:
#MLP AFTER MRMR
#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(X_upt, Y, test_size=0.20, random_state=1)

#MODEL CREATION
model=MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(150,100,50), 
                    random_state=1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accMLP=str(accuracy_score(y_test, y_pred))
conf_sensitivityMLP = (TP / float(TP + FN))
conf_specificityMLP = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityMLP,2)}') 
print(f'Specificity: {round(conf_specificityMLP,2)}') 


Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#SVM AFTER MRMR
#TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(X_upt, Y, test_size=0.20, random_state=1)

#MODEL CREATION
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred=SVCClf.predict(X_test)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(y_test, y_pred)))
cm=confusion_matrix(y_test, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("F1 score: " + str(f1_score(y_test, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accSVM=str(accuracy_score(y_test, y_pred))
conf_sensitivitySVM = (TP / float(TP + FN))
conf_specificitySVM = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivitySVM,2)}') 
print(f'Specificity: {round(conf_specificitySVM,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 1]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#KMM AFTER MRMR

#MODEL CREATION
kmm = KMeans(n_clusters=5,init='k-means++')
kmm.fit(sx)
y_pred=kmm.predict(sx)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(Y, y_pred)))
cm=confusion_matrix(Y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(Y, y_pred)))
print("F1 score: " + str(f1_score(Y, y_pred,average='micro')))
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
accKMR=str(accuracy_score(Y, y_pred))
conf_sensitivityKMR = (TP / float(TP + FN))
conf_specificityKMR = (TN / float(TN + FP))
print(f'Sensitivity: {round(conf_sensitivityKMR,2)}') 
print(f'Specificity: {round(conf_specificityKMR,2)}') 

Accuracy score: 0.6

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 0 5 0]
 [0 0 5 0 0]
 [0 0 0 0 5]]
F1 score: 0.6
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
#FCM AFTER MRMR

#MODEL CREATION
fcm = FCM(n_clusters=5)
fcm.fit(sx)
y_pred=fcm.predict(sx)


#CALCULATING METRICES
print("Accuracy score: " + str(accuracy_score(Y, y_pred)))
cm=confusion_matrix(Y, y_pred)
print("\nConfusion matrix: \n" + str(confusion_matrix(Y, y_pred)))
print("F1 score: " + str(f1_score(Y, y_pred,average='micro')))
TP1 = cm[1][1]
TN1 = cm[0][0]
FP1 = cm[0][1]
FN1 = cm[1][0]
accFCR=str(accuracy_score(Y, y_pred))
conf_sensitivityFCR = (TP1 / float(TP1 + FN1))
conf_specificityFCR = (TN1 / float(TN1 + FP1))
print(f'Sensitivity: {round(conf_sensitivityFCR,2)}') 
print(f'Specificity: {round(conf_specificityFCR,2)}') 

Accuracy score: 1.0

Confusion matrix: 
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]
F1 score: 1.0
Sensitivity: 1.0
Specificity: 1.0


In [ ]:
pip install hmmlearn


In [ ]:
from hmmlearn import hmm

In [ ]:
x1=X_upt.loc[0:4,:]
x2=X_upt.loc[5:9,:]
x3=X_upt.loc[10:14,:]
x4=X_upt.loc[15:19,:]
x5=X_upt.loc[20:24,:]

In [ ]:
y1=Y.loc[0:4]
y2=Y.loc[5:9]
y3=Y.loc[10:14]
y4=Y.loc[15:19]
y5=Y.loc[20:24]

In [ ]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.2,random_state=1)
x_train2,x_test2,y_train2,y_test2=train_test_split(x2,y2,test_size=0.2,random_state=1)
x_train3,x_test3,y_train3,y_test3=train_test_split(x3,y3,test_size=0.2,random_state=1)
x_train4,x_test4,y_train4,y_test4=train_test_split(x4,y4,test_size=0.2,random_state=1)
x_train5,x_test5,y_train5,y_test5=train_test_split(x5,y5,test_size=0.2,random_state=1)

In [ ]:
sc=MinMaxScaler()
x_train1=sc.fit_transform(x_train1)
x_test1=sc.fit_transform(x_test1)
x_train2=sc.fit_transform(x_train2)
x_test2=sc.fit_transform(x_test2)
x_train3=sc.fit_transform(x_train3)
x_test3=sc.fit_transform(x_test3)
x_train4=sc.fit_transform(x_train4)
x_test4=sc.fit_transform(x_test4)
x_train5=sc.fit_transform(x_train5)
x_test5=sc.fit_transform(x_test5)

In [ ]:
h1=hmm.GaussianHMM()
h1.fit(x_train1)
pred1 = h1.predict(x_test1)

In [ ]:
h2=hmm.GaussianHMM()
h2.fit(x_train2)
pred2 = h2.predict(x_test2)

In [ ]:
h3=hmm.GaussianHMM()
h3.fit(x_train3)
pred3 = h3.predict(x_test3)

In [ ]:
h4=hmm.GaussianHMM()
h4.fit(x_train4)
pred4 = h4.predict(x_test4)

In [ ]:
h5=hmm.GaussianHMM()
h5.fit(x_train5)
pred5 = h5.predict(x_test5)

In [ ]:
# Accuracy Score

accuracy1=accuracy_score(y_test1,pred1)
accuracy2=accuracy_score(y_test1,pred2)
accuracy3=accuracy_score(y_test1,pred3)
accuracy4=accuracy_score(y_test1,pred4)
accuracy5=accuracy_score(y_test1,pred5)
print('The accuracy score for Class 0',accuracy1)
print('The accuracy score for Class 1',accuracy2)
print('The accuracy score for Class 2',accuracy3)
print('The accuracy score for Class 3',accuracy4)
print('The accuracy score for Class 4',accuracy5)

The accuracy score for Class 0 1.0
The accuracy score for Class 1 1.0
The accuracy score for Class 2 1.0
The accuracy score for Class 3 1.0
The accuracy score for Class 4 1.0


In [ ]:
print('The Metrics for Class 0:')

# F1 score
print("F1 score: " + str(f1_score(y_test1,pred1,average='micro'))) 

# Confusion Matrix Computation
cm1=confusion_matrix(y_test1, pred1,labels=[1,0])
print("\nConfusion matrix: \n" + str(cm1))

# Sensitivity And Specificity Calculation

TP1 = cm1[1][1]
TN1 = cm1[0][0]
FP1 = cm1[0][1]
FN1 = cm1[1][0]

conf_sensitivity1 = (TP1 / float(TP1 + FN1))
print(f'Sensitivity: {round(conf_sensitivity1,2)}')

The Metrics for Class 0:
F1 score: 1.0

Confusion matrix: 
[[0 0]
 [0 1]]
Sensitivity: 1.0


In [ ]:
print('The Metrics for Class 1:')

# F1 score
print("F1 score: " + str(f1_score(y_test1,pred2,average='micro'))) 

# Confusion Matrix Computation
cm2=confusion_matrix(y_test1, pred2,labels=[1,0])
print("\nConfusion matrix: \n" + str(cm2))

# Sensitivity And Specificity Calculation

TP2 = cm2[1][1]
TN2 = cm2[0][0]
FP2 = cm2[0][1]
FN2 = cm2[1][0]

conf_sensitivity2 = (TP2 / float(TP2 + FN2))
print(f'Sensitivity: {round(conf_sensitivity2,2)}') 

The Metrics for Class 1:
F1 score: 1.0

Confusion matrix: 
[[0 0]
 [0 1]]
Sensitivity: 1.0


In [ ]:
print('The Metrics for Class 2:')

# F1 score
print("F1 score: " + str(f1_score(y_test1,pred3,average='micro'))) 

# Confusion Matrix Computation
cm3=confusion_matrix(y_test1, pred3,labels=[1,0])
print("\nConfusion matrix: \n" + str(cm3))

# Sensitivity And Specificity Calculation

TP3 = cm3[1][1]
TN3 = cm3[0][0]
FP3 = cm3[0][1]
FN3 = cm3[1][0]

conf_sensitivity3 = (TP3 / float(TP3 + FN3))
print(f'Sensitivity: {round(conf_sensitivity3,2)}') 

The Metrics for Class 2:
F1 score: 1.0

Confusion matrix: 
[[0 0]
 [0 1]]
Sensitivity: 1.0


In [ ]:
print('The Metrics for Class 3:')

# F1 score
print("F1 score: " + str(f1_score(y_test1,pred4,average='micro'))) 

# Confusion Matrix Computation
cm4=confusion_matrix(y_test1, pred4,labels=[1,0])
print("\nConfusion matrix: \n" + str(cm4))

# Sensitivity And Specificity Calculation

TP4 = cm4[1][1]
TN4 = cm4[0][0]
FP4 = cm4[0][1]
FN4 = cm4[1][0]

conf_sensitivity4 = (TP2 / float(TP4 + FN4))
print(f'Sensitivity: {round(conf_sensitivity4,2)}') 

The Metrics for Class 3:
F1 score: 1.0

Confusion matrix: 
[[0 0]
 [0 1]]
Sensitivity: 1.0


In [ ]:
print('The Metrics for Class 4:')

# F1 score
print("F1 score: " + str(f1_score(y_test1,pred5,average='micro'))) 

# Confusion Matrix Computation
cm5=confusion_matrix(y_test1, pred5,labels=[1,0])
print("\nConfusion matrix: \n" + str(cm5))

# Sensitivity And Specificity Calculation

TP5 = cm5[1][1]
TN5 = cm5[0][0]
FP5 = cm5[0][1]
FN5 = cm5[1][0]

conf_sensitivity5 = (TP2 / float(TP2 + FN2))
print(f'Sensitivity: {round(conf_sensitivity5,2)}') 

The Metrics for Class 4:
F1 score: 1.0

Confusion matrix: 
[[0 0]
 [0 1]]
Sensitivity: 1.0
